"""norm_name and source_cursors

Revision ID: ad2fe9ad7678
Revises: be58299bcb02
Create Date: 2026-06-15 08:35:56.537790
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ad2fe9ad7678'
down_revision: str | None = 'be58299bcb02'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_cursors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lane_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=60), nullable=False),
    sa.Column('cursor', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lane_id', 'source_key', name='uq_source_cursor_lane_source')
    )
    op.create_index(op.f('ix_source_cursors_lane_id'), 'source_cursors', ['lane_id'], unique=False)
    # Add with a temporary server default so existing rows satisfy NOT NULL, then
    # backfill the real normalised names and drop the default (model has none).
    op.add_column(
        'leads',
        sa.Column('norm_name', sa.String(length=300), nullable=False, server_default=''),
    )
    op.create_index(op.f('ix_leads_norm_name'), 'leads', ['norm_name'], unique=False)

    # Backfill norm_name for existing leads using the same normaliser as ingest.
    from app.services.dedupe import normalize_name

    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, company FROM leads")).fetchall()
    for lead_id, company in rows:
        conn.execute(
            sa.text("UPDATE leads SET norm_name = :n WHERE id = :id"),
            {"n": normalize_name(company or ""), "id": lead_id},
        )
    op.alter_column('leads', 'norm_name', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_norm_name'), table_name='leads')
    op.drop_column('leads', 'norm_name')
    op.drop_index(op.f('ix_source_cursors_lane_id'), table_name='source_cursors')
    op.drop_table('source_cursors')
    # ### end Alembic commands ###
