"""initial schema

Revision ID: dc5eda7de07a
Revises: 
Create Date: 2026-06-14 17:53:20.908922
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = 'dc5eda7de07a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lanes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lanes_name'), 'lanes', ['name'], unique=True)
    op.create_table('suppression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_or_domain', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppression_email_or_domain'), 'suppression', ['email_or_domain'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lane_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('stage', sa.Enum('SOURCED', 'QUALIFIED', 'SCORED', 'ENRICHED', 'READY', 'REJECTED', name='lead_stage', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('SOURCED', 'QUALIFIED', 'RESEARCHED', 'PREPPED', 'QUEUED', 'SENT', 'REPLIED', 'CALL_BOOKED', 'AUDIT_SOLD', 'DELIVERED', 'RETAINER', 'LOST', 'REJECTED', 'SUPPRESSED', name='lead_status', native_enum=False, length=40), nullable=False),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('reject_overridden', sa.Boolean(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('gap_score', sa.Float(), nullable=True),
    sa.Column('reachability_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=560), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lane_id', 'dedupe_key', name='uq_lead_lane_dedupe')
    )
    op.create_index(op.f('ix_leads_dedupe_key'), 'leads', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_leads_domain'), 'leads', ['domain'], unique=False)
    op.create_index(op.f('ix_leads_final_score'), 'leads', ['final_score'], unique=False)
    op.create_index(op.f('ix_leads_lane_id'), 'leads', ['lane_id'], unique=False)
    op.create_index(op.f('ix_leads_stage'), 'leads', ['stage'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('LEAD_CREATED', 'SOURCE_HIT_ADDED', 'QUALIFIED', 'REJECTED', 'OVERRIDDEN', 'SCORED', 'RESEARCHED', 'GEO_CHECKED', 'CONTACT_RESOLVED', 'EVIDENCE_UPLOADED', 'EMAIL_DRAFTED', 'EMAIL_QUEUED', 'EMAIL_SENT', 'REPLY_DETECTED', 'CALL_BOOKED', 'STAGE_CHANGED', 'STATUS_CHANGED', 'NOTE', name='activity_type', native_enum=False, length=40), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_lead_id'), 'activity_log', ['lead_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='email_confidence', native_enum=False, length=40), nullable=True),
    sa.Column('source', sa.Enum('RESEARCH', 'PATTERN', 'VERIFICATION_API', 'MANUAL', 'LINKEDIN_FIRST', name='contact_source', native_enum=False, length=40), nullable=True),
    sa.Column('decision_maker_name', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_lead_id'), 'contacts', ['lead_id'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('touch_no', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=400), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'QUEUED', 'SENT', 'REPLIED', 'CANCELLED', name='email_status', native_enum=False, length=40), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmail_thread_id', sa.String(length=120), nullable=True),
    sa.Column('gmail_draft_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_lead_id'), 'emails', ['lead_id'], unique=False)
    op.create_index(op.f('ix_emails_status'), 'emails', ['status'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('engine', sa.String(length=40), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_lead_id'), 'evidence', ['lead_id'], unique=False)
    op.create_table('geo_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=40), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('prospect_named', sa.Boolean(), nullable=False),
    sa.Column('prospect_recommended', sa.Boolean(), nullable=False),
    sa.Column('competitors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('cited_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('hook_type', sa.Enum('ABSENCE', 'MISREPRESENTATION', 'WEAK_PRESENCE', 'NO_GAP', name='geo_hook_type', native_enum=False, length=40), nullable=True),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_checks_lead_id'), 'geo_checks', ['lead_id'], unique=False)
    op.create_table('research_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('specialisms', sa.Text(), nullable=True),
    sa.Column('high_ticket_services', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('decision_maker_name', sa.String(length=200), nullable=True),
    sa.Column('decision_maker_role', sa.String(length=200), nullable=True),
    sa.Column('human_hook', sa.Text(), nullable=True),
    sa.Column('marketing_sophistication', sa.Text(), nullable=True),
    sa.Column('emails_found', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('pages_fetched', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('model_used', sa.String(length=80), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_briefs_lead_id'), 'research_briefs', ['lead_id'], unique=False)
    op.create_table('source_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=60), nullable=False),
    sa.Column('source_ref', sa.String(length=300), nullable=True),
    sa.Column('raw_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_hits_lead_id'), 'source_hits', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_hits_lead_id'), table_name='source_hits')
    op.drop_table('source_hits')
    op.drop_index(op.f('ix_research_briefs_lead_id'), table_name='research_briefs')
    op.drop_table('research_briefs')
    op.drop_index(op.f('ix_geo_checks_lead_id'), table_name='geo_checks')
    op.drop_table('geo_checks')
    op.drop_index(op.f('ix_evidence_lead_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_emails_status'), table_name='emails')
    op.drop_index(op.f('ix_emails_lead_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_contacts_lead_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_activity_log_lead_id'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_stage'), table_name='leads')
    op.drop_index(op.f('ix_leads_lane_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_final_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_domain'), table_name='leads')
    op.drop_index(op.f('ix_leads_dedupe_key'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppression_email_or_domain'), table_name='suppression')
    op.drop_table('suppression')
    op.drop_index(op.f('ix_lanes_name'), table_name='lanes')
    op.drop_table('lanes')
    # ### end Alembic commands ###
